"""Validate a provisional cold-N2 screen point and emit Eilmer Lua inputs."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path


ALLOWED_T0_K = (285.0, 295.0, 305.0)
ALLOWED_WALL = ("adiabatic", "280", "300", "320")
ALLOWED_INTENSITY = (0.005, 0.01, 0.05)
ALLOWED_LENGTH_M = (0.0001, 0.001, 0.005)
ALLOWED_MESH = ("coarse", "medium", "fine")
ALLOWED_SWEEP = ("startup", "shutdown")


def exact_member(value: float, allowed: tuple[float, ...], name: str) -> float:
    for candidate in allowed:
        if math.isclose(value, candidate, rel_tol=0.0, abs_tol=1.0e-12):
            return candidate
    raise SystemExit(f"{name} must be one of {allowed}; got {value}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pa-pa", type=float, required=True)
    parser.add_argument("--npr", type=float, required=True)
    parser.add_argument("--t0-k", type=float, required=True)
    parser.add_argument("--wall", choices=ALLOWED_WALL, required=True)
    parser.add_argument("--turbulence-intensity", type=float, required=True)
    parser.add_argument("--length-scale-m", type=float, required=True)
    parser.add_argument("--mesh", choices=ALLOWED_MESH, required=True)
    parser.add_argument("--sweep", choices=ALLOWED_SWEEP, required=True)
    parser.add_argument("--lua-output", type=Path, required=True)
    parser.add_argument("--json-output", type=Path, required=True)
    args = parser.parse_args()

    if not math.isfinite(args.pa_pa) or args.pa_pa <= 0.0:
        raise SystemExit("--pa-pa must be a finite positive measured or user-declared value")
    if not math.isfinite(args.npr) or args.npr <= 1.0:
        raise SystemExit("--npr must be finite and greater than one")
    t0_k = exact_member(args.t0_k, ALLOWED_T0_K, "--t0-k")
    intensity = exact_member(
        args.turbulence_intensity, ALLOWED_INTENSITY, "--turbulence-intensity"
    )
    length_m = exact_member(args.length_scale_m, ALLOWED_LENGTH_M, "--length-scale-m")
    p0_pa = args.npr * args.pa_pa
    wall_temperature_k = None if args.wall == "adiabatic" else float(args.wall)

    payload = {
        "classification": "provisional_assumed_screen_not_experimental_match",
        "gas": "N2_ideal_gas_with_Eilmer_CEA_transport",
        "ambient_pressure_Pa": args.pa_pa,
        "NPR": args.npr,
        "stagnation_pressure_Pa": p0_pa,
        "stagnation_pressure_rule": "P0=NPR*Pa",
        "stagnation_temperature_K": t0_k,
        "wall_type": "adiabatic" if wall_temperature_k is None else "fixed_temperature",
        "wall_temperature_K": wall_temperature_k,
        "turbulence_intensity_fraction": intensity,
        "turbulence_length_scale_m": length_m,
        "mesh_level": args.mesh,
        "sweep_direction": args.sweep,
        "wall_material": None,
        "wall_thickness_m": None,
        "conjugate_heat_transfer": False,
        "physics_accepted": False,
        "training_eligible": False,
    }
    args.json_output.write_text(json.dumps(payload, indent=2) + "\n", encoding="ascii")
    lua_wall_temperature = "nil" if wall_temperature_k is None else f"{wall_temperature_k:.17g}"
    args.lua_output.write_text(
        "-- Generated by prepare_run.py; do not edit in an artifact directory.\n"
        "screen = {\n"
        f"  pa_Pa = {args.pa_pa:.17g},\n"
        f"  npr = {args.npr:.17g},\n"
        f"  p0_Pa = {p0_pa:.17g},\n"
        f"  T0_K = {t0_k:.17g},\n"
        f"  wall_type = '{'adiabatic' if wall_temperature_k is None else 'fixed_temperature'}',\n"
        f"  wall_temperature_K = {lua_wall_temperature},\n"
        f"  turbulence_intensity = {intensity:.17g},\n"
        f"  turbulence_length_scale_m = {length_m:.17g},\n"
        f"  mesh_level = '{args.mesh}'\n"
        "}\n",
        encoding="ascii",
    )


if __name__ == "__main__":
    main()
